services:
  db:
    image: postgres
    container_name: db
    hostname: db
    # user: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=atnad
      - POSTGRES_DB=audit
    networks:
      db_net:
        ipv4_address: 172.20.0.2
    volumes:
        - ./create.sql:/docker-entrypoint-initdb.d/a.sql

networks:
  db_net:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"
